### PR TITLE
Added TX initialization, card is fully initialized and sends back AWAKE

### PR DESCRIPTION
**Pull request by rv32ima**

### CODE REVIEW

**Comment by rv32ima** [comment]
image

Note: the TX implementation is VERY bad. I haven't ensured that all of the memory is actually freed and that we're not leaking anything, but this gets us to a point where the FW can be read from disk, init uCode can be loaded, and hardware is ready. As well, rx packets are not handled by the ISR, I'm adding that in ATM.

**Comment by zxystd** [comment]
Thanks for your contribution! I have read all the code you commit, you have fix some problems and add tx functions. But for now this stage, TX and RX transfer are very very import, and I should keep clearly mind, so I will merge this PR after I finish RX and RX transferring. I am a newly driver maker and knows few of MacOS, if there is something wrong in my code or you have good ideas, please help me to figure out. Thanks for your joining. Keep in contact. Also, are you a Chinese?

**Comment by rv32ima** [comment]
Of course! I'm happy to contribute. As well, no. 

On a sidenote, I've just gotten page allocation to work (and we can now receive events from the card). It seems that IOMbufNaturalMemoryCursor can't pull a physical DMA address if it's not tied to a PCI device/other device (which is understandable). 
image

Strangely, the rxq->free_count keeps getting set to 0, which probably isn't the intended behavior of IWLTransport::rxSqRestock, but I can't tell.

**Comment by zxystd** [comment]
Great job!! I have try to alloc mbuf by mbuf_allocpacket, it is really not work, maybe it should alloc by pci device and then it would be map. Now I have merge your commits and push to the repo, and add tx function implement, but send command is still not work, card can response, but it is wrong, I think it is not really transfer full command to the card or the RX have some issues. Thanks for your work.

**Comment by zxystd** [comment]
These days I am trying to find ways to fake an 80211Interface so the native client can communicate with our driver, and we don't even to write another user client. But up to now, there is no further progress in this way. I have write an interface, set the interface sub type to 80211interface, and I know how the IOCTL command dispatch, but I don't know how does the system recognize IO80211Family is load, and the wifi panel show. Do you know something about this?

**Pull request merged**
